spring:
   application:
      name: vet-clinic
   datasource:
      url: jdbc:h2:file:~/VetClinic
      driverClassName: org.h2.Driver
      username: sa
      password: 
      initialization-mode: always
      continue-on-error: true
   jpa:
      generate-ddl: false
      properties:
         hibernate:
            jdbc:
               lob:
                  non_contextual_creation: true
            format_sql: true
      show-sql: true
      hibernate:
         ddl-auto: update
   jackson:
      serialization:
         fail-on-empty-beans: false
      parser:
         allow-single-quotes: true
         
   h2:
      console:
         enabled: true
         path: /h2
